name: Build and Deploy Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build publish-confluence
      run: npm run build
      
    - name: Generate diagrams for documentation
      run: |
        cd docs
        npm ci
        npm run build:diagram
        cd ..
      
    - name: Run publish-confluence on docs
      run: |
        cd docs
        node ../dist/cli.js publish --dry-run ./docs-output
      
    - name: Copy generated docs to public directory
      run: |
        mkdir -p public
        cp -r index.html public/
        cp -r docs/docs-output/spaces public/docs
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
